// src/components/Header.jsx
import React from "react";

export default function Header({ onTrackerClick, onExpenseClick }) {
    return (
        <div className="flex gap-2 mb-4">
            <h1 className="text-2xl border-2 p-2 text-center justify-center me-auto mx-4 hover:cursor-default">
                Spend<span className="font-semibold">Smart</span>
            </h1>
            <button
                className="border-2 w-32 text-lg hover:bg-cyan-700 transition-all"
                onClick={onTrackerClick}
            >
                New Tracker
            </button>
            <button
                className="border-2 mr-4 w-32 text-lg hover:bg-sky-700 transition-all"
                onClick={onExpenseClick}
            >
                New Expense
            </button>
        </div>
    );
}

// src/app/header/header.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
})
export class HeaderComponent {
  @Output() addTrackerClick = new EventEmitter<void>();

  onAddTrackerClick() {
    this.addTrackerClick.emit();
  }
}

<div class="flex gap-2 mb-4">
  <h1
    class="text-2xl lg:text-5xl border-2 p-2 text-center justify-center me-auto mx-4 hover:cursor-default"
  >
    Spend<span class="font-semibold">Smart</span>
  </h1>
  <button
    class="border-2 mr-4 w-32 text-lg lg:text-2xl lg:w-48 hover:bg-cyan-700 transition-all"
    (click)="onAddTrackerClick()"
  >
    New Tracker
  </button>
</div>
