// src/components/AddExpenseModal .jsx
import React, { useRef } from "react";
import { useBudgets } from "../contexts/BudgetsContext";

export default function AddExpenseModal({
    show,
    handleClose,
    defaultBudgetId,
}) {
    const descriptionRef = useRef();
    const amountRef = useRef();
    const budgetIdRef = useRef();
    const { addExpense, budgets } = useBudgets();

    function handleSubmit(e) {
        e.preventDefault();
        addExpense({
            description: descriptionRef.current.value,
            amount: parseFloat(amountRef.current.value),
            budgetId: budgetIdRef.current.value,
        });
        handleClose();
    }

    return (
        <div
            className={`${
                show ? "visible" : "hidden"
            } fixed top-0 left-0 right-0 z-50  w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-[calc(100%-1rem)] max-h-full`}
        >
            <div className="relative w-full max-w-md max-h-full">
                <div className="relative bg-white rounded-lg shadow dark:bg-gray-700">
                    <button
                        type="button"
                        className="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center dark:hover:bg-gray-800 dark:hover:text-white"
                        data-modal-hide="authentication-modal"
                        onClick={handleClose}
                    >
                        <svg
                            aria-hidden="true"
                            className="w-5 h-5"
                            fill="currentColor"
                            viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg"
                        >
                            <path
                                fill-rule="evenodd"
                                d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
                                clip-rule="evenodd"
                            ></path>
                        </svg>
                        <span className="sr-only">Close modal</span>
                    </button>
                    <div className="px-6 py-6 lg:px-8">
                        <h3 className="mb-4 text-xl font-medium text-gray-900 dark:text-white">
                            New Expense
                        </h3>
                        <form className="space-y-6" onSubmit={handleSubmit}>
                            <div>
                                <label
                                    for="description"
                                    className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                                >
                                    Name
                                </label>
                                <input
                                    type="text"
                                    name="description"
                                    id="description"
                                    className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400"
                                    placeholder="Entertainment"
                                    ref={descriptionRef}
                                    required
                                />
                            </div>
                            <div>
                                <label
                                    for="max"
                                    className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                                >
                                    Amount
                                </label>
                                <input
                                    type="number"
                                    name="amount"
                                    id="amount"
                                    placeholder="200"
                                    className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                                    ref={amountRef}
                                    required
                                    step={0.01}
                                />
                            </div>
                            <div>
                                <label
                                    for="budgetId"
                                    className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
                                >
                                    Budget
                                </label>
                                <select
                                    defaultValue={defaultBudgetId}
                                    id="budgetId"
                                    className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-600 dark:border-gray-500 dark:placeholder-gray-400 dark:text-white"
                                    ref={budgetIdRef}
                                    required
                                    step={0.01}
                                    {budgets.map((budget) => (
                                        <option
                                            key={budget.id}
                                            value={budget.id}
                                        >
                                            {budget.name}
                                        </option>
                                    ))}
                                />
                            </div>
                            <div className="flex justify-end">
                                <button
                                    type="submit"
                                    className="w-full text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                                >
                                    Add Budget
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    );
}

// src/app/components/add-expense-modal/add-expense-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import firebase from 'firebase/compat/app';
import { IBudget } from 'src/app/shared/models/interfaces';
import { BudgetsService } from 'src/app/shared/services/budgets.service';

@Component({
  selector: 'app-add-expense-modal',
  templateUrl: './add-expense-modal.component.html',
})
export class AddExpenseModalComponent {
  constructor(private budgetsService: BudgetsService) {}
  @Input() user!: firebase.User | null;
  @Input() budget!: IBudget;
  @Output() closeModal = new EventEmitter<void>();

  handleClose() {
    this.closeModal.emit();
  }

  handleSubmit(f: any) {
    if (this.user)
      this.budgetsService.addExpense(f.value, this.budget, this.user.uid);
    this.handleClose();
  }
}

<div
  class="fixed top-0 left-0 right-0 z-50 w-full p-4 md:p-5 lg:p-6 overflow-x-hidden overflow-y-auto md:inset-0 h-full max-h-full bg-slate-700/[0.6]"
>
  <div
    class="modal relative m-auto w-full max-w-md md:max-w-lg lg:max-w-xl xl:max-w-2xl max-h-full"
  >
    <div class="relative bg-white rounded-lg shadow-2xl">
      <button
        type="button"
        class="absolute top-3 right-2.5 text-gray-400 bg-transparent hover:bg-gray-100 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center"
        data-modal-hide="authentication-modal"
        (click)="handleClose()"
      >
        <svg
          aria-hidden="true"
          class="w-5 h-5 fill-gray-600"
          viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            fill="evenodd"
            d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z"
            clip="evenodd"
          ></path>
        </svg>
      </button>
      <div class="px-6 py-6 lg:px-8">
        <h3
          class="mb-4 text-xl md:text-2xl lg:text-3xl font-medium text-gray-500"
        >
          New Expense
        </h3>
        <form #f="ngForm" class="space-y-6" (ngSubmit)="handleSubmit(f)">
          <div>
            <label
              for="title"
              class="block mb-2 text-sm sm:text-md md:text-lg lg:text-xl font-medium text-gray-600"
              >Title</label
            >
            <input
              type="text"
              name="title"
              id="title"
              class="bg-gray-100 border border-gray-300 text-gray-900 text-sm sm:text-md md:text-lg lg:text-xl rounded-lg block w-full p-2.5"
              placeholder="Restaurant Bill"
              ngModel
              required
            />
          </div>
          <div>
            <label
              for="amount"
              class="block mb-2 text-sm sm:text-md md:text-lg lg:text-xl font-medium text-gray-900"
            >
              Amount
            </label>
            <input
              type="number"
              name="amount"
              id="amount"
              placeholder="20"
              class="bg-gray-100 border border-gray-300 text-gray-900 text-sm sm:text-md md:text-lg lg:text-xl rounded-lg block w-full p-2.5"
              ngModel
              required
              step="{0.01}"
            />
          </div>
          <div>
            <label
              for="date"
              class="block mb-2 text-sm sm:text-md md:text-lg lg:text-xl font-medium text-gray-900"
            >
              Date
            </label>
            <input
              type="date"
              name="date"
              id="date"
              class="bg-gray-100 border border-gray-300 text-gray-900 text-sm sm:text-md md:text-lg lg:text-xl rounded-lg block w-full p-2.5"
              ngModel
              required
              step="{0.01}"
            />
          </div>
          <div class="flex justify-end">
            <button
              type="submit"
              class="w-full text-white bg-cyan-400 hover:bg-cyan-500 focus:ring-4 focus:outline-none font-medium rounded-lg text-sm sm:text-md md:text-lg lg:text-xl px-5 py-2.5 text-center"
            >
              Add Expense
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
